name: build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Build
      run: |
        mkdir build
        cd build
        javac ../src/*.java ../src/sdis/*.java ../src/sdis/*/*.java -cp ../src -d .
